// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sfmjlmtphbazznfasluh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNmbWpsbXRwaGJhenpuZmFzbHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDc0MzAsImV4cCI6MjA3NDQ4MzQzMH0.BuAthJl0CayK_3adlWzFH74W4ColcTH8XTyDF6Dxvhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});